const config = {
  apiBaseURL: 'https://api.tekie.in/graphql/core',
  // apiBaseURL: 'https://tekie-backend-staging.azurewebsites.net/graphql/core',
  // apiBaseURL: 'http://localhost:4002/graphql/core',
  appToken:
    'ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhjSEJKYm1adklqcDdJbTVoYldVaU9pSjBaV3RwWlZSdGN5SXNJblI1Y0dVaU9pSnpkR0YwYVdNaWZTd2lhV0YwSWpveE5UZzVOVE13T0RVNExDSmxlSEFpT2pFNU1EVXhNRFk0TlRoOS43ck9ILW5fM2Z1dUR0TWFoTVdJUVhOQS1nejllX216Y0o5VlNOTHd1WmVvOjpleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlTVzVtYnlJNmV5SnBaQ0k2SW1OcmVEZHdlbWc1YmpBd00zb3dkREZvWTNGaU1tUjZjbU1pTENKMWMyVnlibUZ0WlNJNklrOXRSSFZpWlhsNWVTSjlMQ0pwWVhRaU9qRTJPRE15TURFNU5qWXNJbVY0Y0NJNk1UY3hORGMxT1RVMk5uMC5OOURnSWR6NTcwMjJzYzl4bFFvSHFoS1oySTVtczk1TDRsVkRFeG52cEM4',
};

export default config;
